package com.amway.luckydraw.common;

public enum ErrorCode {
  CAMPAIGN_NOT_FOUND,
  CAMPAIGN_NOT_AVAILABLE,
  INVALID_CAMPAIGN_CONFIGURATION,
  DRAW_LIMIT_EXCEEDED,
  INVALID_DRAW_COUNT,
  INVALID_PROBABILITY_CONFIGURATION,
  PRIZE_NOT_FOUND,
  PRIZE_CONCURRENT_MODIFICATION,
  UNAUTHORIZED,
  FORBIDDEN
}
